---
title: ULC Team Resources Site
timezone: UTC
collections:
  groups:
    title: Groups
    output: true
  blog:
    title: Posts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: groups
  values:
    layout: group
tagline: a theme for building simple digital exhibits
description: CollectionBuilder-GH is a template for creating small digital collection
  exhibits on GitHub Pages designed for teaching digital library skills
keywords: ULC, Orbis Cascade Alliance, IR, Archives, OER, Digital Collections
author: dcnb
url: https://dcnb.github.io
baseurl: "/ulc_repo"
repository: https://github.com/dcnb/ulc_repo
fontawesome: true
bootswatch: 
permalink: pretty
